package com.assign.organization.domain.member;

public enum Position {

    INTERN, STAFF, ASSISTANT_SECTION_MANAGER, ADMINISTRATIVE_MANAGER,
    SECTION_CHIEF, CHIEF, MANAGER, MANAGING_DIRECTOR, EXECUTIVE_VICE_PRESIDENT,
    PRESIDENT, VICE_CHAIRMAN, CHAIRMAN
}
